CREATE DATABASE IF NOT EXISTS NA_SECURITY_URL_APP_IMAGE_DATABASE;
CREATE SCHEMA IF NOT EXISTS NA_SECURITY_URL_APP_IMAGE_DATABASE.IMAGE_SCHEMA;
CREATE IMAGE REPOSITORY IF NOT EXISTS NA_SECURITY_URL_APP_IMAGE_DATABASE.IMAGE_SCHEMA.IMAGE_REPO;
